language: python
python:
  - "3.7"
cache: pip
env:
  global:
    - DISABLE_COLLECTSTATIC=1 
    - TELEGRAM_TOKEN=token 
    - DATABASE_URL=sqlite:///:memory:
install:
  - pipenv install --dev
script:
  - make test
